language: ruby

rvm: 2.3.3

cache: bundler

sudo: false

env:
  global:
    secure: v0egYm6XBg1bLHYfNmK6X4uIfGlVm8UmeAYqtj3zi4I7aTVC7aO5CGLjDcfqQqytUlErOaIs1dKJjCXkKFV6OQQJwyWUjmFReg9aXqCN8oydzzoLDAhemoen4w4UVqSk/WcQyZ3l+5PV4A06++nEv6Hu6lpZnlnrpskMwZX7WU2pBnjESO4U6kQ7Dg3y3FRUTCMalqf39PhMaII8cGNx6h8bect+e7viOwLPED7/DAjhpQ7HTPNkFzQw5BhGkHgnosJ4qaR9r5/FVElo0oElVR1LOlDWqo03LEJ/A7ZRyKOmafIVchT6vzDN7HmVEqFovrhCmegZciz1NaMdsEhCGBS3Emwb239JBxlPB8luSxknLTmM8MtCjnDrDo99Fp/DQAgNfPr88Oq/2EDb7hK8885WsfUVDU3RArovGlNjK1jEWdO/jm72IHmxX0DvlaikHYu1xfX0AC6L8SgJqWek+nxOWMqhX0+0/11QS68mU8nA9F7c2IsyXip8VO5RSqsI4iGbpFyHQDpkAfxzF+Be2zobonn6+uWwP711nFyINmtKMRguqwMwPMT/encKq3E67RLj5/P2MBGZLAXzsYsyMGgZgbbPma5YpsgsIft7Hrc8r3abwQdd9mTk/b7L4iNlj8ANQ0kAzrujbI+KSsS+RUq1jUitTAylENiDH7zhFPw=

notifications:
  email: false

branches:
  only:
  - master

before_script:
- chmod +x ./scripts/build.sh
- chmod +x ./scripts/deploy.sh

script: "./scripts/build.sh"

after_success: "./scripts/deploy.sh"
